### ISSUE TITLE
Exception in thread "LWJGL Application" ...

### ISSUE THREAD

**Issue by mstinsky** [timeracers/ColoredMap#5]
With these versions,
Java: 1.8.0_201-b09
BaseMod Version: 5.5.0
Color Map: 2.3.0
I get the following exception:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: rOutline
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: rOutline
	at coloredmap.ColoredMap.createIcon(ColoredMap.java:139)
	at coloredmap.ColoredMap.receivePostInitialize(ColoredMap.java:65)
	at basemod.BaseMod.publishPostInitialize(BaseMod.java:1980)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostInitializeHook.Postfix(PostInitializeHook.java:9)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:300)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

Color Map 2.2.0 works just fine.

**Comment by timeracers** [comment]
As of version 2.3.0 you need BaseMod version 5.9.0, so this is expected. Remember to keep your mods updated.

**Comment by mstinsky** [comment]
Latest BaseMod release is 5.5.0 (https://github.com/daviscook477/BaseMod/releases), am I missing something?

**Comment by timeracers** [comment]
Yes the latest GitHub BaseMod release is 5.5.0 but the latest release of 5.9.0 is on steam, alternatively you can build the repo to generate version 5.9.0.
